<?php

namespace App\Http\Controllers;

use App\Repositories\FloorRepository;
use Illuminate\Http\Request;

class FloorController extends Controller
{

    protected $floor;
    protected $request;

    public function __construct(Request $request, FloorRepository $repository)
    {
        parent::__construct($request, $repository);
    }

    public function add()
    {
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public function all()
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function findById($id)
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }
}
