<?php

namespace App\Http\Controllers;

use App\Repositories\FloorRepository;
use App\Repositories\LabRepository;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class FloorController extends Controller
{

  protected $floor;
  protected $request;
  protected $labRepository;

  public function __construct(Request $request, FloorRepository $repository, LabRepository $labRepository)
  {
    parent::__construct($request, $repository);
    $this->labRepository = $labRepository;
  }

  public function add()
  {
    return parent::add(); // TODO: Change the autogenerated stub
  }

  public function all()
  {
    return parent::all(); // TODO: Change the autogenerated stub
  }

  public function delete($id)
  {
    return parent::delete($id); // TODO: Change the autogenerated stub
  }

  public function findById($id)
  {
    return parent::findById($id); // TODO: Change the autogenerated stub
  }

  public function labs($id)
  {
    $floor = $this->repository->find($id);
    return new Response($floor->labs, Response::HTTP_OK);
  }
}
