<?php
/**
 * Created by PhpStorm.
 * User: samosunaz
 * Date: 13/09/18
 * Time: 09:40
 */

namespace App\Http\Controllers;


use App\Repositories\LabRepository;
use Illuminate\Http\Request;

class LabController extends Controller
{
    protected $repository;
    protected $request;

    public function __construct(Request $request, LabRepository $repository)
    {
        parent::__construct($request, $repository);
    }

    public function add()
    {
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public function all()
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function findById($id)
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }
}