<?php
/**
 * Created by PhpStorm.
 * User: samosunaz
 * Date: 20/09/18
 * Time: 21:10
 */

namespace App\Http\Controllers;


use App\Repositories\MaterialRepository;
use Illuminate\Http\Request;

class MaterialController extends Controller
{
  public function __construct(Request $request, MaterialRepository $repository)
  {
    parent::__construct($request, $repository);
  }

  public function add()
  {
    return parent::add(); // TODO: Change the autogenerated stub
  }

  public function all()
  {
    return parent::all(); // TODO: Change the autogenerated stub
  }

  public function delete($id)
  {
    return parent::delete($id); // TODO: Change the autogenerated stub
  }

  public function findById($id)
  {
    return parent::findById($id); // TODO: Change the autogenerated stub
  }
}