<?php
/**
 * Created by PhpStorm.
 * User: samosunaz
 * Date: 20/09/18
 * Time: 19:19
 */

namespace App\Http\Controllers;


use App\Repositories\RoleRepository;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    public function __construct(Request $request, RoleRepository $repository)
    {
        parent::__construct($request, $repository);
    }

    public function add()
    {
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public function all()
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function findById($id)
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }
}